### ISSUE TITLE
Arrays of length one are not considered arrays

### ISSUE THREAD

**Issue by pmj714** [pitt-rnel/pyrtma#32]
If you have a message with a definition of something like 
```
constants:
     DIMENSIONS: val

message:
   fields:
      positions: float[DIMENSIONS]
```
I DIMENSIONS has the value of one, the resulting type in python will be float not list[float].
So if DIMENSIONS is any value greater than 1, then you can do
`for pos in msg.positions:` or anything else indexing into the list, but if DIMENSIONS is 1 then you cannot do any indexing.
